export interface City {
    name: string;
    state: string;
    stateCode: string;
    slug: string; // e.g. "houston-tx"
}

// Top 200+ US cities by population — covers every state and all major metros
export const CITIES: City[] = [
    // --- Top 50 metros ---
    { name: "New York", state: "New York", stateCode: "NY", slug: "new-york-ny" },
    { name: "Los Angeles", state: "California", stateCode: "CA", slug: "los-angeles-ca" },
    { name: "Chicago", state: "Illinois", stateCode: "IL", slug: "chicago-il" },
    { name: "Houston", state: "Texas", stateCode: "TX", slug: "houston-tx" },
    { name: "Phoenix", state: "Arizona", stateCode: "AZ", slug: "phoenix-az" },
    { name: "Philadelphia", state: "Pennsylvania", stateCode: "PA", slug: "philadelphia-pa" },
    { name: "San Antonio", state: "Texas", stateCode: "TX", slug: "san-antonio-tx" },
    { name: "San Diego", state: "California", stateCode: "CA", slug: "san-diego-ca" },
    { name: "Dallas", state: "Texas", stateCode: "TX", slug: "dallas-tx" },
    { name: "Austin", state: "Texas", stateCode: "TX", slug: "austin-tx" },
    { name: "Jacksonville", state: "Florida", stateCode: "FL", slug: "jacksonville-fl" },
    { name: "Fort Worth", state: "Texas", stateCode: "TX", slug: "fort-worth-tx" },
    { name: "San Jose", state: "California", stateCode: "CA", slug: "san-jose-ca" },
    { name: "Columbus", state: "Ohio", stateCode: "OH", slug: "columbus-oh" },
    { name: "Charlotte", state: "North Carolina", stateCode: "NC", slug: "charlotte-nc" },
    { name: "Indianapolis", state: "Indiana", stateCode: "IN", slug: "indianapolis-in" },
    { name: "San Francisco", state: "California", stateCode: "CA", slug: "san-francisco-ca" },
    { name: "Seattle", state: "Washington", stateCode: "WA", slug: "seattle-wa" },
    { name: "Denver", state: "Colorado", stateCode: "CO", slug: "denver-co" },
    { name: "Washington", state: "District of Columbia", stateCode: "DC", slug: "washington-dc" },
    { name: "Nashville", state: "Tennessee", stateCode: "TN", slug: "nashville-tn" },
    { name: "Oklahoma City", state: "Oklahoma", stateCode: "OK", slug: "oklahoma-city-ok" },
    { name: "El Paso", state: "Texas", stateCode: "TX", slug: "el-paso-tx" },
    { name: "Boston", state: "Massachusetts", stateCode: "MA", slug: "boston-ma" },
    { name: "Portland", state: "Oregon", stateCode: "OR", slug: "portland-or" },
    { name: "Las Vegas", state: "Nevada", stateCode: "NV", slug: "las-vegas-nv" },
    { name: "Memphis", state: "Tennessee", stateCode: "TN", slug: "memphis-tn" },
    { name: "Louisville", state: "Kentucky", stateCode: "KY", slug: "louisville-ky" },
    { name: "Baltimore", state: "Maryland", stateCode: "MD", slug: "baltimore-md" },
    { name: "Milwaukee", state: "Wisconsin", stateCode: "WI", slug: "milwaukee-wi" },
    { name: "Albuquerque", state: "New Mexico", stateCode: "NM", slug: "albuquerque-nm" },
    { name: "Tucson", state: "Arizona", stateCode: "AZ", slug: "tucson-az" },
    { name: "Fresno", state: "California", stateCode: "CA", slug: "fresno-ca" },
    { name: "Sacramento", state: "California", stateCode: "CA", slug: "sacramento-ca" },
    { name: "Mesa", state: "Arizona", stateCode: "AZ", slug: "mesa-az" },
    { name: "Kansas City", state: "Missouri", stateCode: "MO", slug: "kansas-city-mo" },
    { name: "Atlanta", state: "Georgia", stateCode: "GA", slug: "atlanta-ga" },
    { name: "Omaha", state: "Nebraska", stateCode: "NE", slug: "omaha-ne" },
    { name: "Colorado Springs", state: "Colorado", stateCode: "CO", slug: "colorado-springs-co" },
    { name: "Raleigh", state: "North Carolina", stateCode: "NC", slug: "raleigh-nc" },
    { name: "Long Beach", state: "California", stateCode: "CA", slug: "long-beach-ca" },
    { name: "Virginia Beach", state: "Virginia", stateCode: "VA", slug: "virginia-beach-va" },
    { name: "Miami", state: "Florida", stateCode: "FL", slug: "miami-fl" },
    { name: "Oakland", state: "California", stateCode: "CA", slug: "oakland-ca" },
    { name: "Minneapolis", state: "Minnesota", stateCode: "MN", slug: "minneapolis-mn" },
    { name: "Tampa", state: "Florida", stateCode: "FL", slug: "tampa-fl" },
    { name: "Tulsa", state: "Oklahoma", stateCode: "OK", slug: "tulsa-ok" },
    { name: "Arlington", state: "Texas", stateCode: "TX", slug: "arlington-tx" },
    { name: "New Orleans", state: "Louisiana", stateCode: "LA", slug: "new-orleans-la" },
    { name: "Wichita", state: "Kansas", stateCode: "KS", slug: "wichita-ks" },
    // --- 51–100 ---
    { name: "Cleveland", state: "Ohio", stateCode: "OH", slug: "cleveland-oh" },
    { name: "Bakersfield", state: "California", stateCode: "CA", slug: "bakersfield-ca" },
    { name: "Aurora", state: "Colorado", stateCode: "CO", slug: "aurora-co" },
    { name: "Anaheim", state: "California", stateCode: "CA", slug: "anaheim-ca" },
    { name: "Honolulu", state: "Hawaii", stateCode: "HI", slug: "honolulu-hi" },
    { name: "Santa Ana", state: "California", stateCode: "CA", slug: "santa-ana-ca" },
    { name: "Riverside", state: "California", stateCode: "CA", slug: "riverside-ca" },
    { name: "Corpus Christi", state: "Texas", stateCode: "TX", slug: "corpus-christi-tx" },
    { name: "Lexington", state: "Kentucky", stateCode: "KY", slug: "lexington-ky" },
    { name: "Pittsburgh", state: "Pennsylvania", stateCode: "PA", slug: "pittsburgh-pa" },
    { name: "Stockton", state: "California", stateCode: "CA", slug: "stockton-ca" },
    { name: "St. Paul", state: "Minnesota", stateCode: "MN", slug: "st-paul-mn" },
    { name: "Cincinnati", state: "Ohio", stateCode: "OH", slug: "cincinnati-oh" },
    { name: "Anchorage", state: "Alaska", stateCode: "AK", slug: "anchorage-ak" },
    { name: "Henderson", state: "Nevada", stateCode: "NV", slug: "henderson-nv" },
    { name: "Greensboro", state: "North Carolina", stateCode: "NC", slug: "greensboro-nc" },
    { name: "Plano", state: "Texas", stateCode: "TX", slug: "plano-tx" },
    { name: "Newark", state: "New Jersey", stateCode: "NJ", slug: "newark-nj" },
    { name: "Lincoln", state: "Nebraska", stateCode: "NE", slug: "lincoln-ne" },
    { name: "Orlando", state: "Florida", stateCode: "FL", slug: "orlando-fl" },
    { name: "Irvine", state: "California", stateCode: "CA", slug: "irvine-ca" },
    { name: "Toledo", state: "Ohio", stateCode: "OH", slug: "toledo-oh" },
    { name: "Durham", state: "North Carolina", stateCode: "NC", slug: "durham-nc" },
    { name: "Chula Vista", state: "California", stateCode: "CA", slug: "chula-vista-ca" },
    { name: "Fort Wayne", state: "Indiana", stateCode: "IN", slug: "fort-wayne-in" },
    { name: "Jersey City", state: "New Jersey", stateCode: "NJ", slug: "jersey-city-nj" },
    { name: "St. Petersburg", state: "Florida", stateCode: "FL", slug: "st-petersburg-fl" },
    { name: "Laredo", state: "Texas", stateCode: "TX", slug: "laredo-tx" },
    { name: "Madison", state: "Wisconsin", stateCode: "WI", slug: "madison-wi" },
    { name: "Chandler", state: "Arizona", stateCode: "AZ", slug: "chandler-az" },
    { name: "Buffalo", state: "New York", stateCode: "NY", slug: "buffalo-ny" },
    { name: "Lubbock", state: "Texas", stateCode: "TX", slug: "lubbock-tx" },
    { name: "Scottsdale", state: "Arizona", stateCode: "AZ", slug: "scottsdale-az" },
    { name: "Reno", state: "Nevada", stateCode: "NV", slug: "reno-nv" },
    { name: "Gilbert", state: "Arizona", stateCode: "AZ", slug: "gilbert-az" },
    { name: "Glendale", state: "Arizona", stateCode: "AZ", slug: "glendale-az" },
    { name: "North Las Vegas", state: "Nevada", stateCode: "NV", slug: "north-las-vegas-nv" },
    { name: "Winston-Salem", state: "North Carolina", stateCode: "NC", slug: "winston-salem-nc" },
    { name: "Chesapeake", state: "Virginia", stateCode: "VA", slug: "chesapeake-va" },
    { name: "Norfolk", state: "Virginia", stateCode: "VA", slug: "norfolk-va" },
    // --- 101–150 ---
    { name: "Fremont", state: "California", stateCode: "CA", slug: "fremont-ca" },
    { name: "Garland", state: "Texas", stateCode: "TX", slug: "garland-tx" },
    { name: "Irving", state: "Texas", stateCode: "TX", slug: "irving-tx" },
    { name: "Hialeah", state: "Florida", stateCode: "FL", slug: "hialeah-fl" },
    { name: "Richmond", state: "Virginia", stateCode: "VA", slug: "richmond-va" },
    { name: "Boise", state: "Idaho", stateCode: "ID", slug: "boise-id" },
    { name: "Spokane", state: "Washington", stateCode: "WA", slug: "spokane-wa" },
    { name: "Baton Rouge", state: "Louisiana", stateCode: "LA", slug: "baton-rouge-la" },
    { name: "Des Moines", state: "Iowa", stateCode: "IA", slug: "des-moines-ia" },
    { name: "Tacoma", state: "Washington", stateCode: "WA", slug: "tacoma-wa" },
    { name: "San Bernardino", state: "California", stateCode: "CA", slug: "san-bernardino-ca" },
    { name: "Modesto", state: "California", stateCode: "CA", slug: "modesto-ca" },
    { name: "Fontana", state: "California", stateCode: "CA", slug: "fontana-ca" },
    { name: "Moreno Valley", state: "California", stateCode: "CA", slug: "moreno-valley-ca" },
    { name: "Santa Clarita", state: "California", stateCode: "CA", slug: "santa-clarita-ca" },
    { name: "Fayetteville", state: "North Carolina", stateCode: "NC", slug: "fayetteville-nc" },
    { name: "Birmingham", state: "Alabama", stateCode: "AL", slug: "birmingham-al" },
    { name: "Oxnard", state: "California", stateCode: "CA", slug: "oxnard-ca" },
    { name: "Rochester", state: "New York", stateCode: "NY", slug: "rochester-ny" },
    { name: "Port St. Lucie", state: "Florida", stateCode: "FL", slug: "port-st-lucie-fl" },
    { name: "Grand Rapids", state: "Michigan", stateCode: "MI", slug: "grand-rapids-mi" },
    { name: "Huntsville", state: "Alabama", stateCode: "AL", slug: "huntsville-al" },
    { name: "Salt Lake City", state: "Utah", stateCode: "UT", slug: "salt-lake-city-ut" },
    { name: "Frisco", state: "Texas", stateCode: "TX", slug: "frisco-tx" },
    { name: "Yonkers", state: "New York", stateCode: "NY", slug: "yonkers-ny" },
    { name: "Glendale", state: "California", stateCode: "CA", slug: "glendale-ca" },
    { name: "Huntington Beach", state: "California", stateCode: "CA", slug: "huntington-beach-ca" },
    { name: "McKinney", state: "Texas", stateCode: "TX", slug: "mckinney-tx" },
    { name: "Knoxville", state: "Tennessee", stateCode: "TN", slug: "knoxville-tn" },
    { name: "Amarillo", state: "Texas", stateCode: "TX", slug: "amarillo-tx" },
    { name: "Little Rock", state: "Arkansas", stateCode: "AR", slug: "little-rock-ar" },
    { name: "Akron", state: "Ohio", stateCode: "OH", slug: "akron-oh" },
    { name: "Augusta", state: "Georgia", stateCode: "GA", slug: "augusta-ga" },
    { name: "Montgomery", state: "Alabama", stateCode: "AL", slug: "montgomery-al" },
    { name: "Tallahassee", state: "Florida", stateCode: "FL", slug: "tallahassee-fl" },
    // --- 151–200+ ---
    { name: "Grand Prairie", state: "Texas", stateCode: "TX", slug: "grand-prairie-tx" },
    { name: "Overland Park", state: "Kansas", stateCode: "KS", slug: "overland-park-ks" },
    { name: "Brownsville", state: "Texas", stateCode: "TX", slug: "brownsville-tx" },
    { name: "Tempe", state: "Arizona", stateCode: "AZ", slug: "tempe-az" },
    { name: "Mobile", state: "Alabama", stateCode: "AL", slug: "mobile-al" },
    { name: "Cape Coral", state: "Florida", stateCode: "FL", slug: "cape-coral-fl" },
    { name: "Sioux Falls", state: "South Dakota", stateCode: "SD", slug: "sioux-falls-sd" },
    { name: "Peoria", state: "Arizona", stateCode: "AZ", slug: "peoria-az" },
    { name: "Providence", state: "Rhode Island", stateCode: "RI", slug: "providence-ri" },
    { name: "Vancouver", state: "Washington", stateCode: "WA", slug: "vancouver-wa" },
    { name: "Knoxville", state: "Tennessee", stateCode: "TN", slug: "knoxville-tn" },
    { name: "Chattanooga", state: "Tennessee", stateCode: "TN", slug: "chattanooga-tn" },
    { name: "Oceanside", state: "California", stateCode: "CA", slug: "oceanside-ca" },
    { name: "Fort Collins", state: "Colorado", stateCode: "CO", slug: "fort-collins-co" },
    { name: "Garden Grove", state: "California", stateCode: "CA", slug: "garden-grove-ca" },
    { name: "Rancho Cucamonga", state: "California", stateCode: "CA", slug: "rancho-cucamonga-ca" },
    { name: "Santa Rosa", state: "California", stateCode: "CA", slug: "santa-rosa-ca" },
    { name: "Ontario", state: "California", stateCode: "CA", slug: "ontario-ca" },
    { name: "Elk Grove", state: "California", stateCode: "CA", slug: "elk-grove-ca" },
    { name: "Corona", state: "California", stateCode: "CA", slug: "corona-ca" },
    { name: "Salem", state: "Oregon", stateCode: "OR", slug: "salem-or" },
    { name: "Eugene", state: "Oregon", stateCode: "OR", slug: "eugene-or" },
    { name: "Clarksville", state: "Tennessee", stateCode: "TN", slug: "clarksville-tn" },
    { name: "Cary", state: "North Carolina", stateCode: "NC", slug: "cary-nc" },
    { name: "Murfreesboro", state: "Tennessee", stateCode: "TN", slug: "murfreesboro-tn" },
    { name: "Springfield", state: "Missouri", stateCode: "MO", slug: "springfield-mo" },
    { name: "Midland", state: "Texas", stateCode: "TX", slug: "midland-tx" },
    { name: "Savannah", state: "Georgia", stateCode: "GA", slug: "savannah-ga" },
    { name: "Dayton", state: "Ohio", stateCode: "OH", slug: "dayton-oh" },
    { name: "Joliet", state: "Illinois", stateCode: "IL", slug: "joliet-il" },
    { name: "Naperville", state: "Illinois", stateCode: "IL", slug: "naperville-il" },
    { name: "Bridgeport", state: "Connecticut", stateCode: "CT", slug: "bridgeport-ct" },
    { name: "Stamford", state: "Connecticut", stateCode: "CT", slug: "stamford-ct" },
    { name: "Hartford", state: "Connecticut", stateCode: "CT", slug: "hartford-ct" },
    { name: "Wilmington", state: "Delaware", stateCode: "DE", slug: "wilmington-de" },
    { name: "Charleston", state: "South Carolina", stateCode: "SC", slug: "charleston-sc" },
    { name: "Columbia", state: "South Carolina", stateCode: "SC", slug: "columbia-sc" },
    { name: "Greenville", state: "South Carolina", stateCode: "SC", slug: "greenville-sc" },
    { name: "Billings", state: "Montana", stateCode: "MT", slug: "billings-mt" },
    { name: "Missoula", state: "Montana", stateCode: "MT", slug: "missoula-mt" },
    { name: "Cheyenne", state: "Wyoming", stateCode: "WY", slug: "cheyenne-wy" },
    { name: "Burlington", state: "Vermont", stateCode: "VT", slug: "burlington-vt" },
    { name: "Manchester", state: "New Hampshire", stateCode: "NH", slug: "manchester-nh" },
    { name: "Portland", state: "Maine", stateCode: "ME", slug: "portland-me" },
    { name: "Fargo", state: "North Dakota", stateCode: "ND", slug: "fargo-nd" },
    { name: "Bismarck", state: "North Dakota", stateCode: "ND", slug: "bismarck-nd" },
    { name: "Jackson", state: "Mississippi", stateCode: "MS", slug: "jackson-ms" },
    { name: "Rapid City", state: "South Dakota", stateCode: "SD", slug: "rapid-city-sd" },
    { name: "Topeka", state: "Kansas", stateCode: "KS", slug: "topeka-ks" },
    { name: "Bozeman", state: "Montana", stateCode: "MT", slug: "bozeman-mt" },
    { name: "Charleston", state: "West Virginia", stateCode: "WV", slug: "charleston-wv" },
    { name: "Concord", state: "New Hampshire", stateCode: "NH", slug: "concord-nh" },
    { name: "Rochester", state: "Minnesota", stateCode: "MN", slug: "rochester-mn" },
    { name: "Pensacola", state: "Florida", stateCode: "FL", slug: "pensacola-fl" },
    { name: "Lakeland", state: "Florida", stateCode: "FL", slug: "lakeland-fl" },
    { name: "Fort Myers", state: "Florida", stateCode: "FL", slug: "fort-myers-fl" },
    { name: "Provo", state: "Utah", stateCode: "UT", slug: "provo-ut" },
    { name: "Ogden", state: "Utah", stateCode: "UT", slug: "ogden-ut" },
    { name: "Santa Fe", state: "New Mexico", stateCode: "NM", slug: "santa-fe-nm" },
    { name: "Boca Raton", state: "Florida", stateCode: "FL", slug: "boca-raton-fl" },
    { name: "Sarasota", state: "Florida", stateCode: "FL", slug: "sarasota-fl" },
    { name: "Detroit", state: "Michigan", stateCode: "MI", slug: "detroit-mi" },
    { name: "Ann Arbor", state: "Michigan", stateCode: "MI", slug: "ann-arbor-mi" },
    { name: "Lansing", state: "Michigan", stateCode: "MI", slug: "lansing-mi" },
];

// De-duplicate by slug (some cities appear twice if entered accidentally)
const seen = new Set<string>();
export const UNIQUE_CITIES: City[] = CITIES.filter((c) => {
    if (seen.has(c.slug)) return false;
    seen.add(c.slug);
    return true;
});
